name = "Escherichia_coli_O"
keyword = "ecol_o"
genbank = ""
organism = "Escherichia coli"
taxon = 562
antigen = "O-antigen"
pathway = "Wzx/Wzy or Wzm/Wzt dependent"
prefix = "O"
version = "0.0.1"
id_threshold = 80.0
doi = [ "TBD",]
owner = "Schembri-Laboratory"
repo = "GEOD_Kaptive"
branch = "main"

[contact]
"Samuel Morris" = "uqsmor23@uq.edu.au"

[phenotype_logic."Rough LPS"]
loci = [ "OL*",]
inactive_genes = [ "wzx","wzm", "wzt"]

[phenotype_logic."Rough LPS"]
loci = [ "OL25b",]
inactive_genes = ["wbbL",]

[phenotype_logic."Semi-Rough LPS"]
loci = [ "OL*",]
inactive_genes = [ "wzy",]